var clientList =
  [{ "value": "0", "label": "Sr", "sampleValue": "", "tag": "{{$key}}", "colName": "key", "sortType": "number", "type": "mutual" },
  { "value": "1", "label": "Full Name", "sampleValue": "", "tag": "{{$full_name}}", "colName": "full_name", "sortType": "string", "status": "empty", "requiredCol": ["first_name", "last_name"], "type": "mutual" },
  { "value": "2", "label": "First Name", "sampleValue": "", "tag": "{{$first_name}}", "colName": "first_name", "sortType": "string", "type": "mutual" },
  { "value": "3", "label": "Last Name", "sampleValue": "", "tag": "{{$last_name}}", "colName": "last_name", "sortType": "string", "type": "mutual" },
  { "value": "4", "label": "Date of Birth", "sampleValue": "", "tag": "{{$dateOfBirth}}", "colName": "dateOfBirth", "sortType": "date", "type": "mutual" },
  { "value": "5", "label": "Place of Birth", "sampleValue": "", "tag": "{{$bornCountry}}", "colName": "bornCountry", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_country_list"], "type": "mutual" },
  { "value": "6", "label": "Gender", "sampleValue": "", "tag": "{{$gender}}", "colName": "gender", "sortType": "string", "type": "mutual" },
  { "value": "7", "label": "Preferred Language", "sampleValue": "", "tag": "{{$prefered_lang}}", "colName": "prefered_lang", "sortType": "string", "type": "main" },
  { "value": "8", "label": "Interpreter Required?", "sampleValue": "", "tag": "{{$interpreterReq}}", "colName": "interpreterReq", "sortType": "string", "type": "main" },
  { "value": "9", "label": "NDIS Number", "sampleValue": "", "tag": "{{$ndisNumber}}", "colName": "ndisNumber", "sortType": "string", "type": "mobile" },
  { "value": "10", "label": "Street Address", "sampleValue": "", "tag": "{{$street_address}}", "colName": "street_address", "sortType": "string", "type": "mobile" },
  { "value": "11", "label": "Suburb", "sampleValue": "", "tag": "{{$suburb}}", "colName": "suburb", "sortType": "string", "type": "mutual" },
  { "value": "12", "label": "State", "sampleValue": "", "tag": "{{$state}}", "colName": "state", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_states_list"], "type": "mutual" },
  { "value": "13", "label": "Post Code", "sampleValue": "", "tag": "{{$postCode}}", "colName": "postCode", "sortType": "string", "type": "mutual" },
  { "value": "14", "label": "Email", "sampleValue": "", "tag": "{{$email}}", "colName": "email", "sortType": "string", "type": "mutual" },
  { "value": "15", "label": "Contact Number", "sampleValue": "", "tag": "{{$contactNumber}}", "colName": "contactNumber", "sortType": "string", "type": "mutual" },
  { "value": "16", "label": "NDIS Plan Date", "sampleValue": "", "tag": "{{$ndisPlanDate}}", "colName": "ndisPlanDate", "sortType": "date", "type": "mutual" },
  { "value": "17", "label": "NDIS End Date", "sampleValue": "", "tag": "{{$ndisEndDate}}", "colName": "ndisEndDate", "sortType": "date", "type": "main" },
  { "value": "18", "label": "Plan Manager Name", "sampleValue": "", "tag": "{{$planMangName}}", "colName": "planMangName", "sortType": "string", "type": "main" },
  { "value": "19", "label": "Plan Manager Contact Number", "sampleValue": "", "tag": "{{$planMangNumber}}", "colName": "planMangNumber", "sortType": "string", "type": "main" },
  { "value": "20", "label": "Plan Manager Email", "sampleValue": "", "tag": "{{$planMangEmail}}", "colName": "planMangEmail", "sortType": "string", "type": "mutual" },
  { "value": "21", "label": "Emergency Contact Person Name", "sampleValue": "", "tag": "{{$emConPersonName}}", "colName": "emConPersonName", "sortType": "string", "type": "mutual" },
  { "value": "22", "label": "Relationship to NDIS participant", "sampleValue": "", "tag": "{{$relationToParti}}", "colName": "relationToParti", "sortType": "string", "type": "mutual" },
  { "value": "23", "label": "Contact Person Number", "sampleValue": "", "tag": "{{$emContPersonNumber}}", "colName": "emContPersonNumber", "sortType": "string", "type": "mutual" },
  { "value": "24", "label": "Living Arrangement", "sampleValue": "", "tag": "{{$livingArrang}}", "colName": "livingArrang", "sortType": "string", "type": "main" },
  { "value": "25", "label": "Living Arrangement Other", "sampleValue": "", "tag": "{{$livingArrangOther}}", "colName": "livingArrangOther", "sortType": "string", "type": "mutual" },
  { "value": "26", "label": "Guardian Name", "sampleValue": "", "tag": "{{$guardianName}}", "colName": "guardianName", "sortType": "string", "type": "main" },
  { "value": "27", "label": "Guardian DOB", "sampleValue": "", "tag": "{{$guardianDOB}}", "colName": "guardianDOB", "sortType": "date", "type": "mutual" },
  { "value": "28", "label": "Guardian Home Phone", "sampleValue": "", "tag": "{{$guardianHomePhone}}", "colName": "guardianHomePhone", "sortType": "string", "type": "mutual" },
  { "value": "29", "label": "Guardian Mobile Phone", "sampleValue": "", "tag": "{{$guardianMobNumber}}", "colName": "guardianMobNumber", "sortType": "string", "type": "mutual" },
  { "value": "30", "label": "Guardian Work Phone", "sampleValue": "", "tag": "{{$guardianWorkPhone}}", "colName": "guardianWorkPhone", "sortType": "string", "type": "mutual" },
  { "value": "31", "label": "Guardian Email", "sampleValue": "", "tag": "{{$guardianEmail}}", "colName": "guardianEmail", "sortType": "string", "type": "mutual" },
  { "value": "32", "label": "Guardian Street Address", "sampleValue": "", "tag": "{{$guardianAddress}}", "colName": "guardianAddress", "sortType": "string", "type": "mutual" },
  { "value": "33", "label": "Guardian Suburb", "sampleValue": "", "tag": "{{$guardianSubrub}}", "colName": "guardianSubrub", "sortType": "string", "type": "mutual" },
  { "value": "34", "label": "Guardian State", "sampleValue": "", "tag": "{{$guardianState}}", "colName": "guardianState", "sortType": "string", "type": "mutual" },
  { "value": "35", "label": "Guardian Post Code", "sampleValue": "", "tag": "{{$guardianPostcode}}", "colName": "guardianPostcode", "sortType": "string", "type": "mutual" },
  { "value": "36", "label": "Referral Name", "sampleValue": "", "tag": "{{$makeRefName}}", "colName": "makeRefName", "sortType": "string", "type": "mutual" },
  { "value": "37", "label": "Referral Organization", "sampleValue": "", "tag": "{{$makeRefOrg}}", "colName": "makeRefOrg", "sortType": "string", "type": "mutual" },
  { "value": "38", "label": "Referral Position", "sampleValue": "", "tag": "{{$makeRefPosition}}", "colName": "makeRefPosition", "sortType": "string", "type": "mutual" },
  { "value": "39", "label": "Referral Email", "sampleValue": "", "tag": "{{$makeRefEmail}}", "colName": "makeRefEmail", "sortType": "string", "type": "mutual" },
  { "value": "40", "label": "Referral Street Address", "sampleValue": "", "tag": "{{$makeRefAddress}}", "colName": "makeRefAddress", "sortType": "string", "type": "mutual" },
  { "value": "41", "label": "Referral Subrub", "sampleValue": "", "tag": "{{$makeRefSubrub}}", "colName": "makeRefSubrub", "sortType": "string", "type": "mutual" },
  { "value": "42", "label": "Referral State", "sampleValue": "", "tag": "{{$makeRefState}}", "colName": "makeRefState", "sortType": "string", "type": "mutual" },
  { "value": "43", "label": "Referral Postcode", "sampleValue": "", "tag": "{{$makeRefPostCode}}", "colName": "makeRefPostCode", "sortType": "string", "type": "mutual" },
  { "value": "44", "label": "Referral Phone", "sampleValue": "", "tag": "{{$makeRefPhone}}", "colName": "makeRefPhone", "sortType": "string", "type": "mutual" },
  { "value": "45", "label": "Primary Diagnosis", "sampleValue": "", "tag": "{{$primaryDiagnos}}", "colName": "primaryDiagnos", "sortType": "string", "type": "mutual" },
  { "value": "46", "label": "Secondary Diagnosis", "sampleValue": "", "tag": "{{$secondaryDiagnos}}", "colName": "secondaryDiagnos", "sortType": "string", "type": "mutual" },
  { "value": "47", "label": "Services", "sampleValue": "", "tag": "{{$services}}", "colName": "services_ref_ids", "sortType": "string", "type": "mutual" },
  { "value": "48", "label": "Any risk of self-harm identified", "sampleValue": "", "tag": "{{$anyRisk}}", "colName": "anyRisk", "sortType": "string", "type": "mutual" },
  { "value": "49", "label": "Any risk of self-harm identified - Please specify", "sampleValue": "", "tag": "{{$anyRiskSpecify}}", "colName": "anyRiskSpecify", "sortType": "string", "type": "mutual" },
  { "value": "50", "label": "Harm from others Identified", "sampleValue": "", "tag": "{{$harmFromOther}}", "colName": "harmFromOther", "sortType": "string", "type": "mutual" },
  { "value": "51", "label": "Harm from others Identified - Please specify", "sampleValue": "", "tag": "{{$harmFromOtherSpecify}}", "colName": "harmFromOtherSpecify", "sortType": "string", "type": "mutual" },
  { "value": "52", "label": "Harm to others identified", "sampleValue": "", "tag": "{{$harmToOther}}", "colName": "harmToOther", "sortType": "string", "type": "mutual" },
  { "value": "53", "label": "Harm to others identified - Please specify", "sampleValue": "", "tag": "{{$harmToOtherSpecify}}", "colName": "harmToOtherSpecify", "sortType": "string", "type": "mutual" },
  { "value": "54", "label": "Any pets on the property", "sampleValue": "", "tag": "{{$anyPet}}", "colName": "anyPet", "sortType": "string", "type": "mutual" },
  { "value": "55", "label": "Any pets on the property - Please specify", "sampleValue": "", "tag": "{{$anyPetSpecify}}", "colName": "anyPetSpecify", "sortType": "string", "type": "mutual" },
  { "value": "56", "label": "Any firearms being stored in the property", "sampleValue": "", "tag": "{{$anyFireamers}}", "colName": "anyFireamers", "sortType": "string", "type": "mutual" },
  { "value": "57", "label": "Any firearms being stored in the property - Please specify", "sampleValue": "", "tag": "{{$anyFireamersSpecify}}", "colName": "anyFireamersSpecify", "sortType": "string", "type": "mutual" },
  { "value": "58", "label": "Any history or current of people using alcohol or drugs at the property", "sampleValue": "", "tag": "{{$anyDrugHistory}}", "colName": "anyDrugHistory", "sortType": "string", "type": "mutual" },
  { "value": "59", "label": "Any history or current of people using alcohol or drugs at the property - Please specify", "sampleValue": "", "tag": "{{$anyDrugHistorySpecify}}", "colName": "anyDrugHistorySpecify", "sortType": "string", "type": "mutual" },
  { "value": "60", "label": "Any risk that support staff need to know", "sampleValue": "", "tag": "{{$anyRishToKnow}}", "colName": "anyRishToKnow", "sortType": "string", "type": "mutual" },
  { "value": "61", "label": "Any risk that support staff need to know - Please specify", "sampleValue": "", "tag": "{{$anyRishToKnowSpecify}}", "colName": "anyRishToKnowSpecify", "sortType": "string", "type": "mutual" },
  { "value": "62", "label": "Date of Referral", "sampleValue": "", "tag": "{{$dateOfRef}}", "colName": "dateOfRef", "sortType": "string", "type": "mutual" },
  { "value": "63", "label": "Hearing OK", "sampleValue": "", "tag": "{{$hearing}}", "colName": "hearing", "sortType": "string", "type": "mutual" },
  { "value": "64", "label": "Hearing OK - Hazards identified & actions", "sampleValue": "", "tag": "{{$hearingSpecify}}", "colName": "hearingSpecify", "sortType": "string", "type": "mutual" },
  { "value": "65", "label": "Speech OK", "sampleValue": "", "tag": "{{$speech}}", "colName": "speech", "sortType": "string", "type": "mutual" },
  { "value": "66", "label": "Speech OK - Hazards identified & actions", "sampleValue": "", "tag": "{{$speechSpecify}}", "colName": "speechSpecify", "sortType": "string", "type": "mutual" },
  { "value": "67", "label": "Able to write", "sampleValue": "", "tag": "{{$ableToWrite}}", "colName": "ableToWrite", "sortType": "string", "type": "mutual" },
  { "value": "68", "label": "Able to write - Hazards identified & actions", "sampleValue": "", "tag": "{{$ableToWriteSpecify}}", "colName": "ableToWriteSpecify", "sortType": "string", "type": "mutual" },
  { "value": "69", "label": "English language skills", "sampleValue": "", "tag": "{{$englishSkill}}", "colName": "englishSkill", "sortType": "string", "type": "mutual" },
  { "value": "70", "label": "English language skills - Hazards identified & actions", "sampleValue": "", "tag": "{{$englishSkillSpecify}}", "colName": "englishSkillSpecify", "sortType": "string", "type": "mutual" },
  { "value": "71", "label": "Willing to participate and assist in care", "sampleValue": "", "tag": "{{$willingToParticipate}}", "colName": "willingToParticipate", "sortType": "string", "type": "mutual" },
  { "value": "72", "label": "willing to participate and assist in care - Hazards identified & actions", "sampleValue": "", "tag": "{{$willingToParticipateSpecity}}", "colName": "willingToParticipateSpecity", "sortType": "string", "type": "mutual" },
  { "value": "73", "label": "Oriented in time and place", "sampleValue": "", "tag": "{{$orientation}}", "colName": "orientation", "sortType": "string", "type": "mutual" },
  { "value": "74", "label": "Oriented in time and place - Hazards identified & actions", "sampleValue": "", "tag": "{{$orientationSpecify}}", "colName": "orientationSpecify", "sortType": "string", "type": "mutual" },
  { "value": "75", "label": "Able to accept direction and instruction", "sampleValue": "", "tag": "{{$acceptDiraction}}", "colName": "acceptDiraction", "sortType": "string", "type": "mutual" },
  { "value": "76", "label": "Able to accept direction and instruction - Hazards identified & actions", "sampleValue": "", "tag": "{{$acceptDiractionSpecific}}", "colName": "acceptDiractionSpecific", "sortType": "string", "type": "mutual" },
  { "value": "77", "label": "Short-term memory issues", "sampleValue": "", "tag": "{{$shortMemory}}", "colName": "shortMemory", "sortType": "string", "type": "mutual" },
  { "value": "78", "label": "Short-term memory issues - Hazards identified & actions", "sampleValue": "", "tag": "{{$shortMemorySpecify}}", "colName": "shortMemorySpecify", "sortType": "string", "type": "mutual" },
  { "value": "79", "label": "Walk unaided", "sampleValue": "", "tag": "{{$walkUnaided}}", "colName": "walkUnaided", "sortType": "string", "type": "mutual" },
  { "value": "80", "label": "Walk unaided - Hazards identified & actions", "sampleValue": "", "tag": "{{$walkUnaidedSpecify}}", "colName": "walkUnaidedSpecify", "sortType": "string", "type": "mutual" },
  { "value": "81", "label": "Manages stairs unaided", "sampleValue": "", "tag": "{{$managesStairs}}", "colName": "managesStairs", "sortType": "string", "type": "mutual" },
  { "value": "82", "label": "Manages stairs unaided - Hazards identified & actions", "sampleValue": "", "tag": "{{$managesStairsSpecify}}", "colName": "managesStairsSpecify", "sortType": "string", "type": "mutual" },
  { "value": "83", "label": "Uses walking aid to walk", "sampleValue": "", "tag": "{{$usesWalkingAid}}", "colName": "usesWalkingAid", "sortType": "string", "type": "mutual" },
  { "value": "84", "label": "Uses walking aid to walk - Hazards identified & actions", "sampleValue": "", "tag": "{{$usesWalkingAidSpecify}}", "colName": "usesWalkingAidSpecify", "sortType": "string", "type": "mutual" },
  { "value": "85", "label": "Uses self-propelled wheelchairUses self-propelled wheelchair", "sampleValue": "", "tag": "{{$wheelshair}}", "colName": "wheelshair", "sortType": "string", "type": "mutual" },
  { "value": "86", "label": "Uses self-propelled wheelchair - Hazards identified & actions", "sampleValue": "", "tag": "{{$wheelshairSpecify}}", "colName": "wheelshairSpecify", "sortType": "string", "type": "mutual" },
  { "value": "87", "label": "Uses electric wheelchair/ scooter", "sampleValue": "", "tag": "{{$usesElecWheelChair}}", "colName": "usesElecWheelChair", "sortType": "string", "type": "mutual" },
  { "value": "88", "label": "Uses electric wheelchair/ scooter - Hazards identified & actions", "sampleValue": "", "tag": "{{$usesElecWheelChairSpecify}}", "colName": "usesElecWheelChairSpecify", "sortType": "string", "type": "mutual" },
  { "value": "89", "label": "Transfers independently", "sampleValue": "", "tag": "{{$transferIndep}}", "colName": "transferIndep", "sortType": "string", "type": "mutual" },
  { "value": "90", "label": "Transfers independently - Hazards identified & actions", "sampleValue": "", "tag": "{{$transferIndepSpecify}}", "colName": "transferIndepSpecify", "sortType": "string", "type": "mutual" },
  { "value": "91", "label": "Transfers with supervision", "sampleValue": "", "tag": "{{$transferWithSuper}}", "colName": "transferWithSuper", "sortType": "string", "type": "mutual" },
  { "value": "92", "label": "Transfers with supervision - Hazards identified & actions", "sampleValue": "", "tag": "{{$transferWithSuperSpecify}}", "colName": "transferWithSuperSpecify", "sortType": "string", "type": "mutual" },
  { "value": "93", "label": "Transfers with hoist", "sampleValue": "", "tag": "{{$transferWithHoist}}", "colName": "transferWithHoist", "sortType": "string", "type": "mutual" },
  { "value": "94", "label": "Transfers with hoist - Hazards identified & actions", "sampleValue": "", "tag": "{{$transferWithHoistSpecify}}", "colName": "transferWithHoistSpecify", "sortType": "string", "type": "mutual" },
  { "value": "95", "label": "Bed mobility", "sampleValue": "", "tag": "{{$bedMobility}}", "colName": "bedMobility", "sortType": "string", "type": "mutual" },
  { "value": "96", "label": "Bed mobility - Hazards identified & actions", "sampleValue": "", "tag": "{{$bedMobilitySpecify}}", "colName": "bedMobilitySpecify", "sortType": "string", "type": "mutual" },
  { "value": "97", "label": "Showering", "sampleValue": "", "tag": "{{$showering}}", "colName": "showering", "sortType": "string", "type": "mutual" },
  { "value": "98", "label": "Showering - Hazards identified & actions", "sampleValue": "", "tag": "{{$showeringSpecify}}", "colName": "showeringSpecify", "sortType": "string", "type": "mutual" },
  { "value": "99", "label": "Toileting", "sampleValue": "", "tag": "{{$toileting}}", "colName": "toileting", "sortType": "string", "type": "mutual" },
  { "value": "100", "label": "Toileting - Hazards identified & actions", "sampleValue": "", "tag": "{{$toiletingSpecify}}", "colName": "toiletingSpecify", "sortType": "string", "type": "mutual" },
  { "value": "101", "label": "Grooming", "sampleValue": "", "tag": "{{$grooming}}", "colName": "grooming", "sortType": "string", "type": "mutual" },
  { "value": "102", "label": "Grooming - Hazards identified & actions", "sampleValue": "", "tag": "{{$groomingSpecify}}", "colName": "groomingSpecify", "sortType": "string", "type": "mutual" },
  { "value": "103", "label": "Repositioning in bed", "sampleValue": "", "tag": "{{$repoInBed}}", "colName": "repoInBed", "sortType": "string", "type": "mutual" },
  { "value": "104", "label": "Repositioning in bed - Hazards identified & actions", "sampleValue": "", "tag": "{{$repoInBedSpecify}}", "colName": "repoInBedSpecify", "sortType": "string", "type": "mutual" },
  { "value": "105", "label": "Repositioning in chair", "sampleValue": "", "tag": "{{$repoInChair}}", "colName": "repoInChair", "sortType": "string", "type": "mutual" },
  { "value": "106", "label": "Repositioning in chair - Hazards identified & actions", "sampleValue": "", "tag": "{{$repoInChairSpecify}}", "colName": "repoInChairSpecify", "sortType": "string", "type": "mutual" },
  { "value": "107", "label": "Mouth care", "sampleValue": "", "tag": "{{$mouthCare}}", "colName": "mouthCare", "sortType": "string", "type": "mutual" },
  { "value": "108", "label": "Mouth care - Hazards identified & actions", "sampleValue": "", "tag": "{{$mouthCareSpecify}}", "colName": "mouthCareSpecify", "sortType": "string", "type": "mutual" },
  { "value": "109", "label": "Eating", "sampleValue": "", "tag": "{{$eating}}", "colName": "eating", "sortType": "string", "type": "mutual" },
  { "value": "110", "label": "Eating - Hazards identified & actions", "sampleValue": "", "tag": "{{$eatingSpecify}}", "colName": "eatingSpecify", "sortType": "string", "type": "mutual" },
  { "value": "111", "label": "Skin care", "sampleValue": "", "tag": "{{$skinCare}}", "colName": "skinCare", "sortType": "string", "type": "mutual" },
  { "value": "112", "label": "Skin care - Hazards identified & actions", "sampleValue": "", "tag": "{{$skinCareSpecify}}", "colName": "skinCareSpecify", "sortType": "string", "type": "mutual" },
  { "value": "113", "label": "Physical aggression to support worker", "sampleValue": "", "tag": "{{$phyAggToSp}}", "colName": "phyAggToSp", "sortType": "string", "type": "mutual" },
  { "value": "114", "label": "Physical aggression to support worker - Hazards identified & actions", "sampleValue": "", "tag": "{{$phyAggToSpSpecify}}", "colName": "phyAggToSpSpecify", "sortType": "string", "type": "mutual" },
  { "value": "115", "label": "Verbal aggression to support worker", "sampleValue": "", "tag": "{{$verAggToSp}}", "colName": "verAggToSp", "sortType": "string", "type": "mutual" },
  { "value": "116", "label": "Verbal aggression to support worker - Hazards identified & actions", "sampleValue": "", "tag": "{{$verAggToSpSpecify}}", "colName": "verAggToSpSpecify", "sortType": "string", "type": "mutual" },
  { "value": "117", "label": "Aggression to other clients", "sampleValue": "", "tag": "{{$aggToClients}}", "colName": "aggToClients", "sortType": "string", "type": "mutual" },
  { "value": "118", "label": "Aggression to other clients - Hazards identified & actions", "sampleValue": "", "tag": "{{$aggToClientsSpecify}}", "colName": "aggToClientsSpecify", "sortType": "string", "type": "mutual" },
  { "value": "119", "label": "Aggression with/against objects", "sampleValue": "", "tag": "{{$aggWithObjects}}", "colName": "aggWithObjects", "sortType": "string", "type": "mutual" },
  { "value": "120", "label": "Aggression with/against objects - Hazards identified & actions", "sampleValue": "", "tag": "{{$aggWithObjectsSpecify}}", "colName": "aggWithObjectsSpecify", "sortType": "string", "type": "mutual" },
  { "value": "121", "label": "Self-harm", "sampleValue": "", "tag": "{{$selfHarm}}", "colName": "selfHarm", "sortType": "string", "type": "mutual" },
  { "value": "122", "label": "Self-harm - Hazards identified & actions", "sampleValue": "", "tag": "{{$selfHarmSpecify}}", "colName": "selfHarmSpecify", "sortType": "string", "type": "mutual" },
  { "value": "123", "label": "Substance abuse", "sampleValue": "", "tag": "{{$subAbuse}}", "colName": "subAbuse", "sortType": "string", "type": "mutual" },
  { "value": "124", "label": "Substance abuse - Hazards identified & actions", "sampleValue": "", "tag": "{{$subAbuseSpecify}}", "colName": "subAbuseSpecify", "sortType": "string", "type": "mutual" },
  { "value": "125", "label": "Sexual abuse", "sampleValue": "", "tag": "{{$sexualAbuse}}", "colName": "sexualAbuse", "sortType": "string", "type": "mutual" },
  { "value": "126", "label": "Sexual abuse - Hazards identified & actions", "sampleValue": "", "tag": "{{$sexualAbuseSpecify}}", "colName": "sexualAbuseSpecify", "sortType": "string", "type": "mutual" },
  { "value": "127", "label": "Threats to staff in any way", "sampleValue": "", "tag": "{{$threatsToStaff}}", "colName": "threatsToStaff", "sortType": "string", "type": "mutual" },
  { "value": "128", "label": "Threats to staff in any way - Hazards identified & actions", "sampleValue": "", "tag": "{{$threatsToStaffSpecify}}", "colName": "threatsToStaffSpecify", "sortType": "string", "type": "mutual" },
  { "value": "129", "label": "Use of emotions to achieve goals", "sampleValue": "", "tag": "{{$useEmotionToAcGols}}", "colName": "useEmotionToAcGols", "sortType": "string", "type": "mutual" },
  { "value": "130", "label": "Use of emotions to achieve goals - Hazards identified & actions", "sampleValue": "", "tag": "{{$useEmotionToAcGolsSpecify}}", "colName": "useEmotionToAcGolsSpecify", "sortType": "string", "type": "mutual" },
  { "value": "131", "label": "Status", "sampleValue": "", "tag": "{{$status}}", "colName": "status", "sortType": "string", "type": "mutual" },
  { "value": "132", "label": "Inserted Date & Time", "sampleValue": "29-11-2020, 01:14:08 PM", "tag": "{{$inserted_date_time}}", "colName": "inserted_date_time", "sortType": "date", "status": "empty", "requiredCol": ["inserted_date", "inserted_time"], "type": "mutual" },
  { "value": "133", "label": "Inserted Date", "sampleValue": "29-11-2020, 01:14:08 PM", "tag": "{{$inserted_date}}", "colName": "inserted_date", "sortType": "date", "type": "mutual" },
  { "value": "134", "label": "Inserted Time", "sampleValue": "01:14:08 PM", "tag": "{{$inserted_time}}", "colName": "inserted_time", "sortType": "number", "type": "mutual" },
  { "value": "135", "label": "Inserted By", "sampleValue": "Kashif Fazal", "tag": "{{$inserted_by}}", "colName": "inserted_by", "sortType": "string", "status": "leftJoin", "leftJoinData": ["first_name,last_name", "ep_users"], "type": "mutual" },
  { "value": "136", "label": "Updated Date & Time", "sampleValue": "29-11-2020, 02:53:36 PM", "tag": "{{$updated_date_time}}", "colName": "updated_date_time", "sortType": "date", "status": "empty", "requiredCol": ["updated_date", "updated_time"], "type": "mutual" },
  { "value": "137", "label": "Updated Date", "sampleValue": "29-11-2020", "tag": "{{$updated_date}}", "colName": "updated_date", "sortType": "date", "type": "mutual" },
  { "value": "138", "label": "Updated Time", "sampleValue": "29-11-2020", "tag": "{{$updated_time}}", "colName": "updated_time", "sortType": "number", "type": "mutual" },
  { "value": "139", "label": "Updated By", "sampleValue": "Danish Fazal", "tag": "{{$updated_by}}", "colName": "updated_by", "sortType": "string", "status": "leftJoin", "leftJoinData": ["first_name,last_name", "ep_users"], "type": "mutual" }]
  ;

var clientStatus =
  [{ "value": "active", "label": "Active" }, { "value": "in_active", "label": "In Active" }, { "value": "deleted", "label": "Deleted" }]
  ;

var supportWorkerList =
  [{ "value": "0", "label": "Sr", "sampleValue": "1", "tag": "{{$key}}", "colName": "key", "sortType": "number", "type": "mutual" },
  { "value": "1", "label": "Apply on Job", "sampleValue": "Support Worker Required with IT Related Background", "tag": "{{$job_title}}", "colName": "job_ref_id", "sortType": "string", "status": "leftJoin", "leftJoinData": ["title", "ep_jobs"], "type": "mutual" },
  { "value": "2", "label": "Position", "sampleValue": "Web Developer", "tag": "{{$job_position}}", "colName": "title", "sortType": "string", "status": "leftJoinWithId", "leftJoinWithIdData": ["position", "job_ref_id", "ep_jobs", true], "type": "mutual" },
  { "value": "3", "label": "Timing", "sampleValue": "Contract", "tag": "{{$timing}}", "colName": "timing_ref_id", "sortType": "string", "status": "leftJoinWithId", "leftJoinWithIdData": ["timing_ref_id", "job_ref_id", "ep_jobs", false, "name", "ep_dropdown_general_list"], "type": "mutual" },
  { "value": "4", "label": "Full Name", "sampleValue": "Kashif Fazal", "tag": "{{$full_name}}", "colName": "full_name", "sortType": "string", "status": "empty", "requiredCol": ["first_name", "last_name"], "type": "mutual" },
  { "value": "5", "label": "First Name", "sampleValue": "Kashif", "tag": "{{$first_name}}", "colName": "first_name", "sortType": "string", "type": "mutual" },
  { "value": "6", "label": "Last Name", "sampleValue": "Fazal", "tag": "{{$last_name}}", "colName": "last_name", "sortType": "string", "type": "mutual" },
  { "value": "7", "label": "Street Address", "sampleValue": "2/34 Thomas Street", "tag": "{{$street_address}}", "colName": "street_address", "sortType": "string", "type": "mutual" },
  { "value": "8", "label": "Suburb", "sampleValue": "Camberwell", "tag": "{{$suburb}}", "colName": "suburb", "sortType": "string", "type": "mutual" },
  { "value": "9", "label": "State", "sampleValue": "Victoria", "tag": "{{$state}}", "colName": "state", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_states_list"], "type": "mutual" },
  { "value": "10", "label": "Post Code", "sampleValue": "3124", "tag": "{{$postCode}}", "colName": "postCode", "sortType": "string", "type": "mutual" },
  { "value": "11", "label": "Country", "sampleValue": "Australia", "tag": "{{$country}}", "colName": "country", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_country_list"], "type": "mutual" },
  { "value": "12", "label": "Mobile", "sampleValue": "0315-2048416", "tag": "{{$mobile}}", "colName": "mobile", "sortType": "string", "type": "mutual" },
  { "value": "13", "label": "Email", "sampleValue": "kashiffazal99@gail.com", "tag": "{{$email}}", "colName": "email", "sortType": "string", "type": "mutual" },
  { "value": "14", "label": "Skype ID", "sampleValue": "kashif.fazal99", "tag": "{{$skypeId}}", "colName": "skypeId", "sortType": "string", "type": "mutual" },
  { "value": "15", "label": "Date Of Birth", "sampleValue": "22-05-1990", "tag": "{{$dateOfBirth}}", "colName": "dateOfBirth", "sortType": "date", "type": "mutual" },
  { "value": "16", "label": "Emergency Full Name", "sampleValue": "Chris Crichton", "tag": "{{$emergency_full_name}}", "colName": "emergency_full_name", "sortType": "string", "status": "empty", "requiredCol": ["emergency_first_name", "emergency_last_name"], "type": "mutual" },
  { "value": "17", "label": "Emergency First Name", "sampleValue": "Chris", "tag": "{{$emergency_first_name}}", "colName": "emergency_first_name", "sortType": "string", "type": "mutual" },
  { "value": "18", "label": "Emergency Last Name", "sampleValue": "Crichton", "tag": "{{$emergency_last_name}}", "colName": "emergency_last_name", "sortType": "string", "type": "mutual" },
  { "value": "19", "label": "Emergency Mobile", "sampleValue": "061-0987654", "tag": "{{$emergency_mobile}}", "colName": "emergency_mobile", "sortType": "string", "type": "mutual" },
  { "value": "20", "label": "Emergency Email", "sampleValue": "chris.crichton65@gmail.com", "tag": "{{$emergency_email}}", "colName": "emergency_email", "sortType": "string", "type": "mutual" },
  { "value": "21", "label": "Emergency Relationship", "sampleValue": "Partner", "tag": "{{$emergency_relationship}}", "colName": "emergency_relationship", "sortType": "string", "type": "mutual" },
  { "value": "22", "label": "Emergency Address", "sampleValue": "23 Saunders Court", "tag": "{{$emergency_address}}", "colName": "emergency_address", "sortType": "string", "type": "mutual" },
  { "value": "23", "label": "Emergency Suburb", "sampleValue": "Elphinstone", "tag": "{{$emergency_suburb}}", "colName": "emergency_suburb", "sortType": "string", "type": "mutual" },
  { "value": "24", "label": "Emergency State", "sampleValue": "Victoria", "tag": "{{$emergency_state}}", "colName": "emergency_state", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_states_list"], "type": "mutual" },
  { "value": "25", "label": "Emergency Post Code", "sampleValue": "3448", "tag": "{{$emergency_postCode}}", "colName": "emergency_postCode", "sortType": "string", "type": "mutual" },
  { "value": "26", "label": "Emergency Country", "sampleValue": "Australia", "tag": "{{$emergency_country}}", "colName": "emergency_country", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_country_list"], "type": "mutual" },
  { "value": "27", "label": "First Heard", "sampleValue": "", "tag": "{{$firstHeardAboutYouFirst}}", "colName": "firstHeardAboutYouFirst", "sortType": "string", "type": "mutual" },
  { "value": "28", "label": "First Heard Other", "sampleValue": "", "tag": "{{$firstHeardAboutYouFirstOthers}}", "colName": "firstHeardAboutYouFirstOthers", "sortType": "string", "type": "mutual" },
  { "value": "29", "label": "Currently/Previously worked as SP", "sampleValue": "", "tag": "{{$previouslyWorked}}", "colName": "previouslyWorked", "sortType": "string", "type": "mutual" },
  { "value": "30", "label": "Your Experience", "sampleValue": "", "tag": "{{$aboutExperience}}", "colName": "aboutExperience", "sortType": "string", "type": "mutual" },
  { "value": "31", "label": "Currently Working", "sampleValue": "", "tag": "{{$currentlyWorking}}", "colName": "currentlyWorking", "sortType": "string", "type": "mutual" },
  { "value": "32", "label": "Current Client First Name", "sampleValue": "", "tag": "{{$currentClientFirstName}}", "colName": "currentClientFirstName", "sortType": "string", "type": "mutual" },
  { "value": "33", "label": "Current Client Last Name", "sampleValue": "", "tag": "{{$currentClientLastName}}", "colName": "currentClientLastName", "sortType": "string", "type": "mutual" },
  { "value": "34", "label": "Why Interested?", "sampleValue": "", "tag": "{{$whyInterested}}", "colName": "whyInterested", "sortType": "string", "type": "mutual" },
  { "value": "35", "label": "Receive Email From Us?", "sampleValue": "", "tag": "{{$haveYouReceiveEmail}}", "colName": "haveYouReceiveEmail", "sortType": "string", "type": "mutual" },
  { "value": "36", "label": "Support Services", "sampleValue": "", "tag": "{{$supportServices}}", "colName": "supportServices", "sortType": "string", "type": "mutual" },
  { "value": "37", "label": "Specialized Support Services", "sampleValue": "", "tag": "{{$specialisedSupportServices}}", "colName": "specialisedSupportServices", "sortType": "string", "type": "mutual" },
  { "value": "38", "label": "Secondary employment declaration", "sampleValue": "", "tag": "{{$secondaryEmploymentDeclaration}}", "colName": "secondaryEmploymentDeclaration", "sortType": "string", "type": "mutual" },
  { "value": "39", "label": "First Organization Name", "sampleValue": "", "tag": "{{$first_org_name}}", "colName": "first_org_name", "sortType": "string", "type": "mutual" },
  { "value": "40", "label": "First Organization Address", "sampleValue": "", "tag": "{{$first_org_addr}}", "colName": "first_org_addr", "sortType": "string", "type": "mutual" },
  { "value": "41", "label": "First Organization Suburb", "sampleValue": "", "tag": "{{$first_org_suburb}}", "colName": "first_org_suburb", "sortType": "string", "type": "mutual" },
  { "value": "42", "label": "First Organization State", "sampleValue": "", "tag": "{{$first_org_state}}", "colName": "first_org_state", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_states_list"], "type": "mutual" },
  { "value": "43", "label": "First Organization Post Code", "sampleValue": "", "tag": "{{$first_org_post_code}}", "colName": "first_org_post_code", "sortType": "string", "type": "mutual" },
  { "value": "44", "label": "First Organization Country", "sampleValue": "", "tag": "{{$first_org_country}}", "colName": "first_org_country", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_country_list"], "type": "mutual" },
  { "value": "45", "label": "Second Organization Name", "sampleValue": "", "tag": "{{$second_org_name}}", "colName": "second_org_name", "sortType": "string", "type": "mutual" },
  { "value": "46", "label": "Second Organization Address", "sampleValue": "", "tag": "{{$second_org_addr}}", "colName": "second_org_addr", "sortType": "string", "type": "mutual" },
  { "value": "47", "label": "Second Organization Subrub", "sampleValue": "", "tag": "{{$second_org_suburb}}", "colName": "second_org_suburb", "sortType": "string", "type": "mutual" },
  { "value": "48", "label": "Second Organization State", "sampleValue": "", "tag": "{{$second_org_state}}", "colName": "second_org_state", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_states_list"], "type": "mutual" },
  { "value": "49", "label": "Second Organization Post Code", "sampleValue": "", "tag": "{{$second_org_post_code}}", "colName": "second_org_post_code", "sortType": "string", "type": "mutual" },
  { "value": "50", "label": "Second Organization Country", "sampleValue": "", "tag": "{{$second_org_country}}", "colName": "second_org_country", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_country_list"], "type": "mutual" },
  { "value": "51", "label": "Your Address", "sampleValue": "", "tag": "{{$your_addr}}", "colName": "your_addr", "sortType": "string", "type": "mutual" },
  { "value": "52", "label": "Your Suburb", "sampleValue": "", "tag": "{{$your_suburb}}", "colName": "your_suburb", "sortType": "string", "type": "mutual" },
  { "value": "53", "label": "Your State", "sampleValue": "", "tag": "{{$your_state}}", "colName": "your_state", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_states_list"], "type": "mutual" },
  { "value": "54", "label": "Your Post Code", "sampleValue": "", "tag": "{{$your_post_code}}", "colName": "your_post_code", "sortType": "string", "type": "mutual" },
  { "value": "55", "label": "Your Country", "sampleValue": "", "tag": "{{$your_country}}", "colName": "your_country", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_country_list"], "type": "mutual" },
  { "value": "56", "label": "Your Email", "sampleValue": "", "tag": "{{$your_email}}", "colName": "your_email", "sortType": "string", "type": "mutual" },
  { "value": "57", "label": "Your Mobile", "sampleValue": "", "tag": "{{$your_mobile}}", "colName": "your_mobile", "sortType": "string", "type": "mutual" },
  { "value": "58", "label": "Have or Had Any Disability", "sampleValue": "", "tag": "{{$hadAnyDisability}}", "colName": "hadAnyDisability", "sortType": "string", "type": "mutual" },
  { "value": "59", "label": "Disability Details", "sampleValue": "", "tag": "{{$hadAnyDisabilityDetails}}", "colName": "hadAnyDisabilityDetails", "sortType": "string", "type": "mutual" },
  { "value": "60", "label": "Have or Had Any Injury or Disease", "sampleValue": "", "tag": "{{$injury_disease}}", "colName": "injury_disease", "sortType": "string", "type": "mutual" },
  { "value": "61", "label": "Injury or Disease Details", "sampleValue": "", "tag": "{{$injury_disease_desc}}", "colName": "injury_disease_desc", "sortType": "string", "type": "mutual" },
  { "value": "62", "label": "Own Reliable Car", "sampleValue": "", "tag": "{{$reliableCar}}", "colName": "reliableCar", "sortType": "string", "type": "mutual" },
  { "value": "63", "label": "VIC driving license", "sampleValue": "", "tag": "{{$hac_vic_driving_license}}", "colName": "hac_vic_driving_license", "sortType": "string", "type": "mutual" },
  { "value": "64", "label": "Superannuation Account", "sampleValue": "", "tag": "{{$has_superannuation_ac}}", "colName": "has_superannuation_ac", "sortType": "string", "type": "mutual" },
  { "value": "65", "label": "Availability Days", "sampleValue": "", "tag": "{{$days_availibility_day}}", "colName": "days_availibility_day", "sortType": "string", "type": "mutual" },
  { "value": "66", "label": "Availability From", "sampleValue": "", "tag": "{{$days_availibility_from}}", "colName": "days_availibility_from", "sortType": "string", "type": "mutual" },
  { "value": "67", "label": "Availability To", "sampleValue": "", "tag": "{{$days_availibility_to}}", "colName": "days_availibility_to", "sortType": "string", "type": "mutual" },
  { "value": "68", "label": "Availability N/A", "sampleValue": "", "tag": "{{$days_availibility_na}}", "colName": "days_availibility_na", "sortType": "string", "type": "mutual" },
  { "value": "69", "label": "Australian Citizen", "sampleValue": "", "tag": "{{$australianCitizen}}", "colName": "australianCitizen", "sortType": "string", "type": "mutual" },
  { "value": "70", "label": "Have Visa", "sampleValue": "", "tag": "{{$haveVisa}}", "colName": "haveVisa", "sortType": "string", "type": "mutual" },
  { "value": "71", "label": "Don't Have Visa", "sampleValue": "", "tag": "{{$dontHaveVisaDesc}}", "colName": "dontHaveVisaDesc", "sortType": "string", "type": "mutual" },
  { "value": "72", "label": "Visa Class or subclass", "sampleValue": "", "tag": "{{$visaClassSubClass}}", "colName": "visaClassSubClass", "sortType": "string", "type": "mutual" },
  { "value": "73", "label": "Visa Grant Number", "sampleValue": "", "tag": "{{$visaGrantNumber}}", "colName": "visaGrantNumber", "sortType": "string", "type": "mutual" },
  { "value": "74", "label": "Visa Expiry Date", "sampleValue": "", "tag": "{{$visaExpDate}}", "colName": "visaExpDate", "sortType": "date", "type": "mutual" },
  { "value": "75", "label": "Passport Number", "sampleValue": "", "tag": "{{$passportNumber}}", "colName": "passportNumber", "sortType": "string", "type": "mutual" },
  { "value": "76", "label": "Passport Country of Issue", "sampleValue": "", "tag": "{{$countryOfIssue}}", "colName": "countryOfIssue", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_country_list"], "type": "mutual" },
  { "value": "77", "label": "Any Restrictions On Visa", "sampleValue": "", "tag": "{{$restrictionsOnVisa}}", "colName": "restrictionsOnVisa", "sortType": "string", "type": "mutual" },
  { "value": "78", "label": "Passport Date of Issue", "sampleValue": "", "tag": "{{$passportIssueDate}}", "colName": "passportIssueDate", "sortType": "date", "type": "mutual" },
  { "value": "79", "label": "Passport Date of Expiry", "sampleValue": "", "tag": "{{$passportExpDate}}", "colName": "passportExpDate", "sortType": "date", "type": "mutual" },
  { "value": "80", "label": "Gender", "sampleValue": "", "tag": "{{$gender}}", "colName": "gender", "sortType": "string", "type": "mutual" },
  { "value": "81", "label": "Gender Self Description", "sampleValue": "", "tag": "{{$genderSelfDesc}}", "colName": "genderSelfDesc", "sortType": "string", "type": "mutual" },
  { "value": "82", "label": "Identify as Aboriginal or Torres", "sampleValue": "", "tag": "{{$identify}}", "colName": "identify", "sortType": "string", "type": "mutual" },
  { "value": "83", "label": "Culturally/Linguistically", "sampleValue": "", "tag": "{{$culturally}}", "colName": "culturally", "sortType": "string", "type": "mutual" },
  { "value": "84", "label": "Born in Australia?", "sampleValue": "", "tag": "{{$wherYouBorn}}", "colName": "wherYouBorn", "sortType": "string", "type": "mutual" },
  { "value": "85", "label": "Country of Birth", "sampleValue": "", "tag": "{{$bornCountry}}", "colName": "bornCountry", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_country_list"], "type": "mutual" },
  { "value": "86", "label": "Born Other Country", "sampleValue": "", "tag": "{{$otherBornCountry}}", "colName": "otherBornCountry", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_country_list"], "type": "mutual" },
  { "value": "87", "label": "Is English the main language", "sampleValue": "", "tag": "{{$isEnglishMain}}", "colName": "isEnglishMain", "sortType": "string", "type": "mutual" },
  { "value": "88", "label": "Other Languages", "sampleValue": "", "tag": "{{$otherLanguageSpeak}}", "colName": "otherLanguageSpeak", "sortType": "string", "type": "mutual" },
  { "value": "89", "label": "Main Language", "sampleValue": "", "tag": "{{$mainLanguage}}", "colName": "mainLanguage", "sortType": "string", "type": "mutual" },
  { "value": "90", "label": "Other Main Language", "sampleValue": "", "tag": "{{$otherMainLanguage}}", "colName": "otherMainLanguage", "sortType": "string", "type": "mutual" },
  { "value": "91", "label": "Identify as Lesbian, Gay, Bi-Sexual, Transgender, Intersex and / or Queer?", "sampleValue": "", "tag": "{{$identifyAs}}", "colName": "identifyAs", "sortType": "string", "type": "mutual" },
  { "value": "92", "label": "Work Experience", "sampleValue": "", "tag": "{{$workExp}}", "colName": "workExp", "sortType": "string", "type": "mutual" },
  { "value": "93", "label": "Current Employer Name", "sampleValue": "", "tag": "{{$nameOfEmployer}}", "colName": "nameOfEmployer", "sortType": "string", "type": "mutual" },
  { "value": "94", "label": "Current Employer Address", "sampleValue": "", "tag": "{{$exp_street_address}}", "colName": "exp_street_address", "sortType": "string", "type": "mutual" },
  { "value": "95", "label": "Current Employer Suburb", "sampleValue": "", "tag": "{{$exp_suburb}}", "colName": "exp_suburb", "sortType": "string", "type": "mutual" },
  { "value": "96", "label": "Current Employer State", "sampleValue": "", "tag": "{{$exp_state}}", "colName": "exp_state", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_states_list"], "type": "mutual" },
  { "value": "97", "label": "Current Employer Post Code", "sampleValue": "", "tag": "{{$exp_postCode}}", "colName": "exp_postCode", "sortType": "string", "type": "mutual" },
  { "value": "98", "label": "Current Employer Country", "sampleValue": "", "tag": "{{$exp_country}}", "colName": "exp_country", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_country_list"], "type": "mutual" },
  { "value": "99", "label": "Current Work Role", "sampleValue": "", "tag": "{{$currentWorkRole}}", "colName": "currentWorkRole", "sortType": "string", "type": "mutual" },
  { "value": "100", "label": "Current Work Skill", "sampleValue": "", "tag": "{{$currentWorkSkills}}", "colName": "currentWorkSkills", "sortType": "string", "type": "mutual" },
  { "value": "101", "label": "Last Employer Name", "sampleValue": "", "tag": "{{$nameOfLastEmp}}", "colName": "nameOfLastEmp", "sortType": "string", "type": "mutual" },
  { "value": "102", "label": "Last Employer Address", "sampleValue": "", "tag": "{{$exp_last_street_address}}", "colName": "exp_last_street_address", "sortType": "string", "type": "mutual" },
  { "value": "103", "label": "Last Employer Suburb", "sampleValue": "", "tag": "{{$exp_last_suburb}}", "colName": "exp_last_suburb", "sortType": "string", "type": "mutual" },
  { "value": "104", "label": "Last Employer State", "sampleValue": "", "tag": "{{$exp_last_state}}", "colName": "exp_last_state", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_states_list"], "type": "mutual" },
  { "value": "105", "label": "Last Employer Post Code", "sampleValue": "", "tag": "{{$exp_last_postCode}}", "colName": "exp_last_postCode", "sortType": "string", "type": "mutual" },
  { "value": "106", "label": "Last Employer Country", "sampleValue": "", "tag": "{{$exp_last_country}}", "colName": "exp_last_country", "sortType": "string", "status": "leftJoin", "leftJoinData": ["name", "ep_dropdown_country_list"], "type": "mutual" },
  { "value": "107", "label": "Year of Stop Working", "sampleValue": "", "tag": "{{$yearOfStopWorking}}", "colName": "yearOfStopWorking", "sortType": "string", "type": "mutual" },
  { "value": "108", "label": "Previous Role", "sampleValue": "", "tag": "{{$previousRole}}", "colName": "previousRole", "sortType": "string", "type": "mutual" },
  { "value": "109", "label": "Previous Skill", "sampleValue": "", "tag": "{{$previousSkills}}", "colName": "previousSkills", "sortType": "string", "type": "mutual" },
  { "value": "110", "label": "Undertaken Volunteer", "sampleValue": "", "tag": "{{$undertakenVolunteer}}", "colName": "undertakenVolunteer", "sortType": "string", "type": "mutual" },
  { "value": "111", "label": "Type of Volunteering", "sampleValue": "", "tag": "{{$typeOfVolunteering}}", "colName": "typeOfVolunteering", "sortType": "string", "type": "mutual" },
  { "value": "112", "label": "Other Type of Volunteering", "sampleValue": "", "tag": "{{$otherVolunteering}}", "colName": "otherVolunteering", "sortType": "string", "type": "mutual" },
  { "value": "113", "label": "Skills on Volunteering", "sampleValue": "", "tag": "{{$skillsOnVolunteering}}", "colName": "skillsOnVolunteering", "sortType": "string", "type": "mutual" },
  { "value": "114", "label": "Is Local References", "sampleValue": "", "tag": "{{$isLocalReferences}}", "colName": "isLocalReferences", "sortType": "string", "type": "mutual" },
  { "value": "115", "label": "Local References Contact No", "sampleValue": "", "tag": "{{$localReferences_contact_no}}", "colName": "localReferences_contact_no", "sortType": "string", "type": "mutual" },
  { "value": "116", "label": "Local References Email", "sampleValue": "", "tag": "{{$localReferences_email_address}}", "colName": "localReferences_email_address", "sortType": "string", "type": "mutual" },
  { "value": "117", "label": "Local References Referee", "sampleValue": "", "tag": "{{$localReferences_name_of_referee}}", "colName": "localReferences_name_of_referee", "sortType": "string", "type": "mutual" },
  { "value": "118", "label": "Local References Organization", "sampleValue": "", "tag": "{{$localReferences_organisation}}", "colName": "localReferences_organisation", "sortType": "string", "type": "mutual" },
  { "value": "119", "label": "Local References Position Held", "sampleValue": "", "tag": "{{$localReferences_position_held}}", "colName": "localReferences_position_held", "sortType": "string", "type": "mutual" },
  { "value": "120", "label": "Criminal Declaration", "sampleValue": "", "tag": "{{$criminal_declaration}}", "colName": "criminal_declaration", "sortType": "string", "type": "mutual" },
  { "value": "121", "label": "Criminal Declaration Description", "sampleValue": "", "tag": "{{$criminal_declaration_desc}}", "colName": "criminal_declaration_desc", "sortType": "string", "type": "mutual" },
  { "value": "122", "label": "Relevant Qualifications", "sampleValue": "", "tag": "{{$relevantQualifications}}", "colName": "relevantQualifications", "sortType": "string", "type": "mutual" },
  { "value": "123", "label": "Type of Qualification", "sampleValue": "", "tag": "{{$typeOfQualification}}", "colName": "typeOfQualification", "sortType": "string", "type": "mutual" },
  { "value": "124", "label": "Other Qualification", "sampleValue": "", "tag": "{{$otherQulification}}", "colName": "otherQulification", "sortType": "string", "type": "mutual" },
  { "value": "125", "label": "Qualification Certificate Name", "sampleValue": "", "tag": "{{$qualCertificateName}}", "colName": "qualCertificateName", "sortType": "string", "type": "mutual" },
  { "value": "126", "label": "Qualification Certificate Year", "sampleValue": "", "tag": "{{$qualCompleteYear}}", "colName": "qualCompleteYear", "sortType": "string", "type": "mutual" },
  { "value": "127", "label": "Qualification Issued By", "sampleValue": "", "tag": "{{$qualSchoolUniName}}", "colName": "qualSchoolUniName", "sortType": "string", "type": "mutual" },
  { "value": "128", "label": "Another Qualification", "sampleValue": "", "tag": "{{$anotherQulification}}", "colName": "anotherQulification", "sortType": "string", "type": "mutual" },
  { "value": "129", "label": "Another Qualification Type", "sampleValue": "", "tag": "{{$anotherTypeOfQualification}}", "colName": "anotherTypeOfQualification", "sortType": "string", "type": "mutual" },
  { "value": "130", "label": "Another Qualification Other", "sampleValue": "", "tag": "{{$anotherOtherQulification}}", "colName": "anotherOtherQulification", "sortType": "string", "type": "mutual" },
  { "value": "131", "label": "Another Qual Certificate Name", "sampleValue": "", "tag": "{{$anotherQualCertificateName}}", "colName": "anotherQualCertificateName", "sortType": "string", "type": "mutual" },
  { "value": "132", "label": "Another Qual Certificate Year", "sampleValue": "", "tag": "{{$anotherQualCompleteYear}}", "colName": "anotherQualCompleteYear", "sortType": "string", "type": "mutual" },
  { "value": "133", "label": "Another Qualification Issued By", "sampleValue": "", "tag": "{{$anotherQualSchoolUniName}}", "colName": "anotherQualSchoolUniName", "sortType": "string", "type": "mutual" },
  { "value": "134", "label": "Have Resume", "sampleValue": "", "tag": "{{$haveResume}}", "colName": "haveResume", "sortType": "string", "type": "mutual" },
  { "value": "135", "label": "Have Student ID Card", "sampleValue": "", "tag": "{{$haveStudentIdCatd}}", "colName": "haveStudentIdCatd", "sortType": "string", "type": "mutual" },
  { "value": "136", "label": "Have Driving License", "sampleValue": "", "tag": "{{$haveDrivingLicense}}", "colName": "haveDrivingLicense", "sortType": "string", "type": "mutual" },
  { "value": "137", "label": "Have Car Insurance", "sampleValue": "", "tag": "{{$haveCarInsurance}}", "colName": "haveCarInsurance", "sortType": "string", "type": "mutual" },
  { "value": "138", "label": "Have Passport Copy", "sampleValue": "", "tag": "{{$havePassportCopy}}", "colName": "havePassportCopy", "sortType": "string", "type": "mutual" },
  { "value": "139", "label": "Have Police Check", "sampleValue": "", "tag": "{{$havePoliceCheck}}", "colName": "havePoliceCheck", "sortType": "string", "type": "mutual" },
  { "value": "140", "label": "Have Working Children Card", "sampleValue": "", "tag": "{{$haveWorkChildrenCard}}", "colName": "haveWorkChildrenCard", "sortType": "string", "type": "mutual" },
  { "value": "141", "label": "Have First Aid Certificate", "sampleValue": "", "tag": "{{$haveFirstAidCertificate}}", "colName": "haveFirstAidCertificate", "sortType": "string", "type": "mutual" },
  { "value": "142", "label": "Have Manual Handling Certificate", "sampleValue": "", "tag": "{{$haveManualHandlingCertificate}}", "colName": "haveManualHandlingCertificate", "sortType": "string", "type": "mutual" },
  { "value": "143", "label": "Have Food Handling Certificate", "sampleValue": "", "tag": "{{$haveFoodHandlingCertificate}}", "colName": "haveFoodHandlingCertificate", "sortType": "string", "type": "mutual" },
  { "value": "144", "label": "Have Evidence of Working Visa", "sampleValue": "", "tag": "{{$haveWorkingOrVisa}}", "colName": "haveWorkingOrVisa", "sortType": "string", "type": "mutual" },
  { "value": "145", "label": "Have NDIS Worker Orientation Completion Certificate", "sampleValue": "", "tag": "{{$haveNDISWorOriComCer}}", "colName": "haveNDISWorOriComCer", "sortType": "string", "type": "mutual" },
  { "value": "146", "label": "Have Diploma of Nursing", "sampleValue": "", "tag": "{{$haveDiplomaOfNursing}}", "colName": "haveDiplomaOfNursing", "sortType": "string", "type": "mutual" },
  { "value": "147", "label": "Have Certificate 3 Disability", "sampleValue": "", "tag": "{{$haveCertificate3Disability}}", "colName": "haveCertificate3Disability", "sortType": "string", "type": "mutual" },
  { "value": "148", "label": "Have Certificate 4 Disability", "sampleValue": "", "tag": "{{$haveCertificate4Disability}}", "colName": "haveCertificate4Disability", "sortType": "string", "type": "mutual" },
  { "value": "149", "label": "Have Certificate 4 Diploma", "sampleValue": "", "tag": "{{$haveCertificate4Diploma}}", "colName": "haveCertificate4Diploma", "sortType": "string", "type": "mutual" },
  { "value": "150", "label": "Have Relevant Qualification", "sampleValue": "", "tag": "{{$haveRelevantQulification}}", "colName": "haveRelevantQulification", "sortType": "string", "type": "mutual" },
  { "value": "151", "label": "Have Other Documents", "sampleValue": "", "tag": "{{$haveOtherDocuments}}", "colName": "haveOtherDocuments", "sortType": "string", "type": "mutual" },
  { "value": "152", "label": "Confirmation on Certification", "sampleValue": "", "tag": "{{$confirmation}}", "colName": "confirmation", "sortType": "string", "type": "mutual" },
  { "value": "153", "label": "Status", "sampleValue": "", "tag": "{{$status}}", "colName": "status", "sortType": "string", "type": "mutual" },
  { "value": "154", "label": "Reject Reason", "sampleValue": "", "tag": "{{$rejectReason}}", "colName": "rejectReason", "sortType": "string", "type": "mutual" },
  { "value": "155", "label": "Is Team Member", "sampleValue": "", "tag": "{{$isTeamMember}}", "colName": "isTeamMember", "sortType": "string", "type": "mutual" },
  { "value": "156", "label": "Team Position", "sampleValue": "", "tag": "{{$teamPosition}}", "colName": "teamPosition", "sortType": "string", "type": "mutual" },
  { "value": "157", "label": "Team Status", "sampleValue": "", "tag": "{{$teamStatus}}", "colName": "teamStatus", "sortType": "string", "type": "mutual" },
  { "value": "158", "label": "Inserted Date & Time", "sampleValue": "29-11-2020, 01:14:08 PM", "tag": "{{$inserted_date_time}}", "colName": "inserted_date_time", "sortType": "date", "status": "empty", "requiredCol": ["inserted_date", "inserted_time"], "type": "mutual" },
  { "value": "159", "label": "Inserted Date", "sampleValue": "29-11-2020, 01:14:08 PM", "tag": "{{$inserted_date}}", "colName": "inserted_date", "sortType": "date", "type": "mutual" },
  { "value": "160", "label": "Inserted Time", "sampleValue": "01:14:08 PM", "tag": "{{$inserted_time}}", "colName": "inserted_time", "sortType": "number", "type": "mutual" },
  { "value": "161", "label": "Inserted By", "sampleValue": "Kashif Fazal", "tag": "{{$inserted_by}}", "colName": "inserted_by", "sortType": "string", "status": "leftJoin", "leftJoinData": ["first_name,last_name", "ep_users"], "type": "mutual" },
  { "value": "162", "label": "Updated Date & Time", "sampleValue": "29-11-2020, 02:53:36 PM", "tag": "{{$updated_date_time}}", "colName": "updated_date_time", "sortType": "date", "status": "empty", "requiredCol": ["updated_date", "updated_time"], "type": "mutual" },
  { "value": "163", "label": "Updated Date", "sampleValue": "29-11-2020", "tag": "{{$updated_date}}", "colName": "updated_date", "sortType": "date", "type": "mutual" },
  { "value": "164", "label": "Updated Time", "sampleValue": "29-11-2020", "tag": "{{$updated_time}}", "colName": "updated_time", "sortType": "number", "type": "mutual" },
  { "value": "165", "label": "Updated By", "sampleValue": "Danish Fazal", "tag": "{{$updated_by}}", "colName": "updated_by", "sortType": "string", "status": "leftJoin", "leftJoinData": ["first_name,last_name", "ep_users"], "type": "mutual" }]
  ;

var supportWorkerListStatus =
  [{ "value": "1", "label": "Applied" },
  { "value": "2", "label": "Shortlisted" },
  { "value": "3", "label": "Contacted" },
  { "value": "4", "label": "Interviewed" },
  { "value": "5", "label": "Hired" },
  { "value": "6", "label": "Rejected" },
  { "value": "7", "label": "On-Hold" },
  { "value": "8", "label": "Deleted" },
  { "value": "9", "label": "Exited" }]
  ;

var company =
  [{ "value": "0", "label": "Sr", "sampleValue": "1", "tag": "{{$key}}", "colName": "key", "sortType": "number", "type": "mutual" },
  { "value": "1", "label": "Company Logo", "sampleValue": "sample_logo.png", "tag": "{{$company_logo}}", "colName": "company_logo", "sortType": "string", "prefixSessionVar": "companyLogoPath", "type": "mutual" },
  { "value": "2", "label": "Company Name", "sampleValue": "Authentic Life Care", "tag": "{{$company_name}}", "colName": "company_name", "sortType": "string", "type": "mutual" },
  { "value": "3", "label": "Company Phone/Mobile", "sampleValue": "+61 3 9014 9846", "tag": "{{$company_phone_mobile}}", "colName": "company_phone_mobile", "sortType": "number", "type": "mutual" },
  { "value": "4", "label": "Company Email", "sampleValue": "support@authenticlifecare.com.au", "tag": "{{$company_email}}", "colName": "company_email", "sortType": "number", "type": "mutual" },
  { "value": "5", "label": "Company Domain", "sampleValue": "authenticlifecare.com.au", "tag": "{{$company_domain_name}}", "colName": "company_domain_name", "sortType": "number", "type": "mutual" },
  { "value": "6", "label": "Company Address", "sampleValue": "22/882 Cooper Street, Somerton, VIC 3062", "tag": "{{$company_address}}", "colName": "company_address", "sortType": "string", "type": "mutual" },
  { "value": "7", "label": "Inserted Date & Time", "sampleValue": "29-11-2020, 01:14:08 PM", "tag": "{{$inserted_date_time}}", "colName": "inserted_date_time", "sortType": "date", "status": "empty", "requiredCol": ["inserted_date", "inserted_time"], "type": "mutual" },
  { "value": "8", "label": "Inserted Date", "sampleValue": "29-11-2020, 01:14:08 PM", "tag": "{{$inserted_date}}", "colName": "inserted_date", "sortType": "date", "type": "mutual" },
  { "value": "9", "label": "Inserted Time", "sampleValue": "01:14:08 PM", "tag": "{{$inserted_time}}", "colName": "inserted_time", "sortType": "number", "type": "mutual" },
  { "value": "10", "label": "Inserted By", "sampleValue": "Kashif Fazal", "tag": "{{$inserted_by}}", "colName": "inserted_by", "sortType": "string", "status": "leftJoin", "leftJoinData": ["first_name,last_name", "ep_users"], "type": "mutual" },
  { "value": "11", "label": "Updated Date & Time", "sampleValue": "29-11-2020, 02:53:36 PM", "tag": "{{$updated_date_time}}", "colName": "updated_date_time", "sortType": "date", "status": "empty", "requiredCol": ["updated_date", "updated_time"], "type": "mutual" },
  { "value": "12", "label": "Updated Date", "sampleValue": "29-11-2020", "tag": "{{$updated_date}}", "colName": "updated_date", "sortType": "date", "type": "mutual" },
  { "value": "13", "label": "Updated Time", "sampleValue": "29-11-2020", "tag": "{{$updated_time}}", "colName": "updated_time", "sortType": "number", "type": "mutual" },
  { "value": "14", "label": "Updated By", "sampleValue": "Danish Fazal", "tag": "{{$updated_by}}", "colName": "updated_by", "sortType": "string", "status": "leftJoin", "leftJoinData": ["first_name,last_name", "ep_users"], "type": "mutual" }]
  ;

//@ "value" - (Required) - Serial of Column
//@ "label" - (Required) - Label of Column in Report
//@ "colName" - (Required) - Name of Column
//@ "sortType" - (Required) - Could be string,date etc
//@ "type" - (Optional) - It's basically not for AUL app but exists for future plan (Maybe if we needed)
//@ "status" - (Optional) - Could be empty,leftJoin etc
//@ "prefixSessionVar" - (Optional) - It's the prefix of value (Before value), it's must be from $_SESSION variable
//*** Required On "leftJoin" - "leftJoinData": ["first_name,last_name", "ep_support_worker_form"]
//????? leftJoinData : ["Columns With Comma Separation","Table Name"]

var timerList =
  [{ "value": "0", "label": "Sr", "sampleValue": "", "tag": "{{$key}}", "colName": "key", "sortType": "number", "type": "mutual" },
  { "value": "1", "label": "Shift Done By - Full Name", "sampleValue": "", "tag": "{{$service_done_by_spw_ref_id}}", "colName": "service_done_by_spw_ref_id", "sortType": "string", "status": "leftJoin", "leftJoinData": ["first_name,last_name", "ep_support_worker_form"], "type": "mutual" },
  { "value": "2", "label": "First SW Name", "sampleValue": "", "tag": "{{$spw_ref_id}}", "colName": "spw_ref_id", "sortType": "string", "status": "leftJoin", "leftJoinData": ["first_name,last_name", "ep_support_worker_form"], "type": "mutual" },
  { "value": "3", "label": "Second SW Name", "sampleValue": "", "tag": "{{$spw2_ref_id}}", "colName": "spw2_ref_id", "sortType": "string", "status": "leftJoin", "leftJoinData": ["first_name,last_name", "ep_support_worker_form"], "type": "mutual" },
  { "value": "4", "label": "Client Full Name", "sampleValue": "", "tag": "{{$client_name}}", "colName": "client_ref_id", "sortType": "string", "status": "leftJoin", "leftJoinData": ["first_name,last_name", "ep_client_form"], "type": "mutual" },
  { "value": "5", "label": "Service Name", "sampleValue": "", "tag": "{{$service_ref_id}}", "colName": "service_ref_id", "sortType": "string", "status": "leftJoin", "leftJoinData": ["code,name", "ep_service_list"], "type": "mutual" },
  { "value": "6", "label": "Shift No", "sampleValue": "", "tag": "{{$shift_no}}", "colName": "service_plaining_ref_id", "sortType": "string", "status": "leftJoin", "leftJoinData": ["shift_no", "ep_service_plaining"], "type": "mutual" },
  { "value": "7", "label": "Start Time - Actual", "sampleValue": "", "tag": "{{$start_time_actual}}", "colName": "start_time_actual", "sortType": "string", "type": "mutual" },
  { "value": "8", "label": "End Time - Actual", "sampleValue": "", "tag": "{{$end_time_actual}}", "colName": "end_time_actual", "sortType": "string", "type": "mutual" },
  { "value": "9", "label": "Start Time", "sampleValue": "", "tag": "{{$start_time}}", "colName": "start_time", "sortType": "string", "type": "mutual" },
  { "value": "10", "label": "End Time", "sampleValue": "", "tag": "{{$end_time}}", "colName": "end_time", "sortType": "string", "type": "mutual" },
  { "value": "11", "label": "Start Time Mod", "sampleValue": "", "tag": "{{$start_time_mod}}", "colName": "start_time_mod", "sortType": "string", "type": "mutual" },
  { "value": "12", "label": "End Time Mod", "sampleValue": "", "tag": "{{$end_time_mod}}", "colName": "end_time_mod", "sortType": "string", "type": "mutual" },
  { "value": "13", "label": "Status", "sampleValue": "", "tag": "{{$status}}", "colName": "status", "sortType": "string", "type": "mutual" },
  { "value": "14", "label": "Inserted Date & Time", "sampleValue": "29-11-2020, 01:14:08 PM", "tag": "{{$inserted_date_time}}", "colName": "inserted_date_time", "sortType": "date", "status": "empty", "requiredCol": ["inserted_date", "inserted_time"], "type": "mutual" },
  { "value": "15", "label": "Inserted Date", "sampleValue": "29-11-2020, 01:14:08 PM", "tag": "{{$inserted_date}}", "colName": "inserted_date", "sortType": "date", "type": "mutual" },
  { "value": "16", "label": "Inserted Time", "sampleValue": "01:14:08 PM", "tag": "{{$inserted_time}}", "colName": "inserted_time", "sortType": "number", "type": "mutual" },
  { "value": "17", "label": "Inserted By", "sampleValue": "Kashif Fazal", "tag": "{{$inserted_by}}", "colName": "inserted_by", "sortType": "string", "status": "leftJoin", "leftJoinData": ["first_name,last_name", "ep_users"], "type": "mutual" },
  { "value": "18", "label": "Updated Date & Time", "sampleValue": "29-11-2020, 02:53:36 PM", "tag": "{{$updated_date_time}}", "colName": "updated_date_time", "sortType": "date", "status": "empty", "requiredCol": ["updated_date", "updated_time"], "type": "mutual" },
  { "value": "19", "label": "Updated Date", "sampleValue": "29-11-2020", "tag": "{{$updated_date}}", "colName": "updated_date", "sortType": "date", "type": "mutual" },
  { "value": "20", "label": "Updated Time", "sampleValue": "29-11-2020", "tag": "{{$updated_time}}", "colName": "updated_time", "sortType": "number", "type": "mutual" },
  { "value": "21", "label": "Updated By", "sampleValue": "Danish Fazal", "tag": "{{$updated_by}}", "colName": "updated_by", "sortType": "string", "status": "leftJoin", "leftJoinData": ["first_name,last_name", "ep_users"], "type": "mutual" }]
  ;

var timerStatus =
  [{ "value": "unreviewed", "label": "Un Reviewed" }, { "value": "reviewed", "label": "Reviewed" }, { "value": "unattended", "label": "Unattended" }, { "value": "deleted", "label": "Deleted" }]
  ;


var appointment =
  [{ "value": "0", "label": "Sr", "sampleValue": "1", "tag": "{{$key}}", "colName": "key", "sortType": "number", "type": "mutual" },
  { "value": "1", "label": "Appointment No", "sampleValue": "APT-0001", "tag": "{{$appointment_no}}", "colName": "appointment_no", "sortType": "string", "type": "mutual" },
  { "value": "2", "label": "Client Name", "sampleValue": "Justine Stroet", "tag": "{{$client_name}}", "colName": "client_ref_id", "sortType": "string", "status": "leftJoin", "leftJoinData": ["first_name,last_name", "ep_client_form"], "type": "mutual" },
  { "value": "3", "label": "Date", "sampleValue": "22-02-2023", "tag": "{{$date}}", "colName": "date", "sortType": "date", "type": "mutual" },
  { "value": "4", "label": "Start Time", "sampleValue": "08:00 AM", "tag": "{{$start_time}}", "colName": "start_time", "sortType": "string", "type": "mutual" },
  { "value": "5", "label": "End Time", "sampleValue": "07:00 PM", "tag": "{{$end_time}}", "colName": "end_time", "sortType": "string", "type": "mutual" },
  { "value": "6", "label": "Title", "sampleValue": "Sample Appointment", "tag": "{{$title}}", "colName": "title", "sortType": "string", "type": "mutual" },
  { "value": "7", "label": "Description", "sampleValue": "Sample Description", "tag": "{{$description}}", "colName": "description", "sortType": "string", "type": "mutual" },
  { "value": "8", "label": "Shift No", "sampleValue": "SPN-0021", "tag": "{{$shift_no}}", "colName": "service_plaining_ref_id", "sortType": "string", "status": "leftJoin", "leftJoinData": ["shift_no", "ep_service_plaining"], "type": "mutual" },
  { "value": "9", "label": "Status", "sampleValue": "Assigned", "tag": "{{$status}}", "colName": "status", "sortType": "string", "type": "mutual" },
  { "value": "10", "label": "Inserted Date & Time", "sampleValue": "29-11-2020, 01:14:08 PM", "tag": "{{$inserted_date_time}}", "colName": "inserted_date_time", "sortType": "date", "status": "empty", "requiredCol": ["inserted_date", "inserted_time"], "type": "mutual" },
  { "value": "11", "label": "Inserted Date", "sampleValue": "29-11-2020, 01:14:08 PM", "tag": "{{$inserted_date}}", "colName": "inserted_date", "sortType": "date", "type": "mutual" },
  { "value": "12", "label": "Inserted Time", "sampleValue": "01:14:08 PM", "tag": "{{$inserted_time}}", "colName": "inserted_time", "sortType": "number", "type": "mutual" },
  { "value": "13", "label": "Inserted By", "sampleValue": "Kashif Fazal", "tag": "{{$inserted_by}}", "colName": "inserted_by", "sortType": "string", "status": "leftJoin", "leftJoinData": ["first_name,last_name", "ep_users"], "type": "mutual" },
  { "value": "14", "label": "Updated Date & Time", "sampleValue": "29-11-2020, 02:53:36 PM", "tag": "{{$updated_date_time}}", "colName": "updated_date_time", "sortType": "date", "status": "empty", "requiredCol": ["updated_date", "updated_time"], "type": "mutual" },
  { "value": "15", "label": "Updated Date", "sampleValue": "29-11-2020", "tag": "{{$updated_date}}", "colName": "updated_date", "sortType": "date", "type": "mutual" },
  { "value": "16", "label": "Updated Time", "sampleValue": "29-11-2020", "tag": "{{$updated_time}}", "colName": "updated_time", "sortType": "number", "type": "mutual" },
  { "value": "17", "label": "Updated By", "sampleValue": "Danish Fazal", "tag": "{{$updated_by}}", "colName": "updated_by", "sortType": "string", "status": "leftJoin", "leftJoinData": ["first_name,last_name", "ep_users"], "type": "mutual" }]
  ;