import { TableColumnFilter, SortableDateInTableData } from '../../../services';

export const ColumnUnReviewedAndReviewed = [{
  title: 'Sr',
  dataIndex: 'key',
  width: '5%',
  fixed: 'left',
  sorter: (a, b) => a.key - b.key,
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} >{a}</div>,
}, {
  title: 'Date',
  dataIndex: 'inserted_date',
  width: '7%',
  fixed: 'left',
  sorter: SortableDateInTableData('inserted_date'),
  ...TableColumnFilter('inserted_date'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} >{a}</div>,
}, {
  title: 'Shift No.',
  dataIndex: 'shift_no',
  width: '7%',
  fixed: 'left',
  sorter: (a, b) => a.shift_no.localeCompare(b.shift_no),
  ...TableColumnFilter('shift_no'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} >{a}</div>,
}, {
  title: 'Request #',
  dataIndex: 'request_no',
  width: '7%',
  sorter: (a, b) => a.request_no.localeCompare(b.request_no),
  ...TableColumnFilter('request_no'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} >{a}</div>,
}, {
  title: 'Support Worker & Partner',
  dataIndex: 'swp_name',
  width: '17%',
  sorter: (a, b) => a.swp_name.localeCompare(b.swp_name),
  ...TableColumnFilter('swp_name'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} >{a}</div>,
}, {
  title: 'Client Name',
  dataIndex: 'client_name',
  width: '11%',
  sorter: (a, b) => a.client_name.localeCompare(b.client_name),
  ...TableColumnFilter('client_name'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} >{a}</div>,
}, {
  title: 'Ac S-Time',
  dataIndex: 'start_time_actual',
  width: '8%',
  sorter: (a, b) => a.start_time_actual.localeCompare(b.start_time_actual),
  ...TableColumnFilter('start_time_actual'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} ><span className="ac_time_color">{a}</span></div>,
}, {
  title: 'Ac E-Time',
  dataIndex: 'end_time_actual',
  width: '8%',
  sorter: (a, b) => a.end_time_actual.localeCompare(b.end_time_actual),
  ...TableColumnFilter('end_time_actual'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} ><span className="ac_time_color">{a}</span></div>,
}, {
  title: 'Ac T-Time',
  dataIndex: 'hour_actual',
  width: '8%',
  sorter: (a, b) => a.hour_actual.localeCompare(b.hour_actual),
  ...TableColumnFilter('hour_actual'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} >{a}</div>,
}, {
  title: 'S-Time',
  dataIndex: 'start_time',
  width: '9%',
  sorter: (a, b) => a.start_time.localeCompare(b.start_time),
  ...TableColumnFilter('start_time'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} ><span className="do_time_color">{a}</span></div>,
}, {
  title: 'E-Time',
  dataIndex: 'end_time',
  width: '9%',
  sorter: (a, b) => a.end_time.localeCompare(b.end_time),
  ...TableColumnFilter('end_time'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} ><span className="do_time_color">{a}</span></div>,
}, {
  title: 'T-Time',
  dataIndex: 'hour',
  width: '7%',
  sorter: (a, b) => a.hour.localeCompare(b.hour),
  ...TableColumnFilter('hour'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} >{a}</div>,
}];

export const ColumnUnattended = [{
  title: 'Sr',
  dataIndex: 'key',
  width: '5%',
  fixed: 'left',
  sorter: (a, b) => a.key - b.key,
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} >{a}</div>,
}, {
  title: 'Date',
  dataIndex: 'inserted_date_formatted',
  width: '8%',
  fixed: 'left',
  sorter: SortableDateInTableData('inserted_date'),
  ...TableColumnFilter('inserted_date_formatted'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} >{a}</div>,
}, {
  title: 'Shift No.',
  dataIndex: 'shift_no',
  width: '8%',
  fixed: 'left',
  sorter: (a, b) => a.shift_no.localeCompare(b.shift_no),
  ...TableColumnFilter('shift_no'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} >{a}</div>,
}, {
  title: 'Request #',
  dataIndex: 'request_no',
  width: '8%',
  sorter: (a, b) => a.request_no.localeCompare(b.request_no),
  ...TableColumnFilter('request_no'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} >{a}</div>,
}, {
  title: 'Support Worker & Partner',
  dataIndex: 'swp_name',
  width: '20%',
  sorter: (a, b) => a.swp_name.localeCompare(b.swp_name),
  ...TableColumnFilter('swp_name'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} >{a}</div>,
}, {
  title: 'Client Name',
  dataIndex: 'client_name',
  width: '13%',
  sorter: (a, b) => a.client_name.localeCompare(b.client_name),
  ...TableColumnFilter('client_name'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} >{a}</div>,
}, {
  title: 'Ac S-Time',
  dataIndex: 'start_time_actual',
  width: '9%',
  sorter: (a, b) => a.start_time_actual.localeCompare(b.start_time_actual),
  ...TableColumnFilter('start_time_actual'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} ><span className="ac_time_color">{a}</span></div>,
}, {
  title: 'Ac E-Time',
  dataIndex: 'end_time_actual',
  width: '9%',
  sorter: (a, b) => a.end_time_actual.localeCompare(b.end_time_actual),
  ...TableColumnFilter('end_time_actual'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} ><span className="ac_time_color">{a}</span></div>,
}, {
  title: 'Ac T-Time',
  dataIndex: 'hour_actual',
  width: '9%',
  sorter: (a, b) => a.hour_actual.localeCompare(b.hour_actual),
  ...TableColumnFilter('hour_actual'),
  render: (a, b) => <div title="Delayed Shift" className={(b.delayStatus === 'true') ? 'delay-row-col' : ''} >{a}</div>,
}];


